# Generated by Django 5.1.7 on 2025-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.IntegerField()),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], max_length=20)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('profile', models.ImageField(upload_to='profile')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
