# Generated by Django 5.1.7 on 2025-04-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRICULTURE_APP', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
