# Generated by Django 5.1.7 on 2025-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRICULTURE_APP', '0005_complaint_is_read_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireLevelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(help_text='Fire intensity or presence level')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IRSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmokeSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.FloatField(help_text='Parts per million')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_percent', models.FloatField(help_text='Moisture level in %')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(help_text='Water level in cm or inches')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
