# Generated by Django 5.1.7 on 2025-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRICULTURE_APP', '0006_firelevelsensor_irsensor_smokesensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firelevelsensor',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='irsensor',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smokesensor',
            name='ppm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='soilmoisturesensor',
            name='moisture_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='waterlevelsensor',
            name='level',
            field=models.IntegerField(),
        ),
    ]
