# Generated by Django 5.1.7 on 2025-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRICULTURE_APP', '0007_alter_firelevelsensor_level_alter_irsensor_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
